### ISSUE TITLE
Help: Reloaded2 cannot open mods

### ISSUE THREAD

**Issue by yougotrespect** [Reloaded-Project/Reloaded-II#341]
**Did you install the Prerequisites?**
yes

**Describe the Issue**
I have no idea so will give my screenshot

**Screenshots**
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/163796092/7b5c856f-ab70-4383-be7a-369ac3d9d464)
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/163796092/711992bd-f0e1-495f-bf9a-d7443e0a322c)
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/163796092/8286ebc0-f6cd-45cd-9bf2-e9f4bcdb2e82)

**Comment by Sewer56** [comment]
`r2:https://github.com/Sewer56/Reloaded.SharedLib.Hooks.ReloadedII/releases/download/1.16.1/Reloaded.Hooks.ReloadedII1.16.1.7z`

Paste this into your browser, see what happens

**Comment by yougotrespect** [comment]
> `r2:https://github.com/Sewer56/Reloaded.SharedLib.Hooks.ReloadedII/releases/download/1.16.1/Reloaded.Hooks.ReloadedII1.16.1.7z`
> 
> Paste this into your browser, see what happens

 I downloaded the file
what do I have to do next?

**Comment by Sewer56** [comment]
Nothing, running after installing should fix the issue.
If it doesn't, let me know.

**Comment by yougotrespect** [comment]
I have trouble after this image
I restarted my computer but still fails
thanks for your help
but seems like my computer cannot use Reloaded2

![image](https://github.com/Reloaded-Project/Reloaded-II/assets/163796092/f8555e57-60af-43db-bec3-9c550449122f)

![image](https://github.com/Reloaded-Project/Reloaded-II/assets/163796092/a13a9d6d-6e18-4e99-afa1-fe4ffc32d993)
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/163796092/8025e0a5-749d-46c9-98c0-4e8c9de0ba82)

[Reloaded] Create Loader | Time: 20ms
[Reloaded] Loading 1 Mod(s).
[Reloaded]
[Reloaded] Loading: Reloaded II Shared Lib: Reloaded.Hooks
[Reloaded] - AppId   : reloaded.sharedlib.hooks
[Reloaded] - LoadTime: 3ms
[Reloaded] Loaded via: C:\Users\justi\OneDrive\바탕 화면\Reloaded-II\Loader\x64\Bootstrapper\Reloaded.Mod.Loader.Bootstrapper.dll
[Reloaded] Current Process Location: D:\SteamLibrary\steamapps\common\P5R\P5R.exe
[Reloaded] Loading 9 Mod(s).
[Reloaded]
[Reloaded] Loading: Library: Reloaded.Memory.Sigscan for Reloaded II
[Reloaded] - AppId   : Reloaded.Memory.SigScan.ReloadedII
[Reloaded] - LoadTime: 3ms
[Reloaded]
[Reloaded] Loading: File Emulation Framework: Base Mod
[Reloaded] - AppId   : reloaded.universal.fileemulationframework
Starting FileEmulationFramework
[R-II SteamHook] SteamAPI_RestartAppIfNecessary hooked successfully.
[R-II SteamHook] SteamAPI_IsSteamRunning hooked successfully.
[Reloaded] - LoadTime: 82ms

**Comment by Sewer56** [comment]
Freezes on load? Weird.
Hmm, can you try a minimal mod setup. Just `Persona Essentials`, nothing else.

**Comment by yougotrespect** [comment]
> Freezes on load? Weird. Hmm, can you try a minimal mod setup. Just `Persona Essentials`, nothing else.


![image](https://github.com/Reloaded-Project/Reloaded-II/assets/163796092/0f30803b-1e5f-4310-887e-b873b6406fe4)
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/163796092/05f5577c-d770-41c8-bf7e-6cb38a4e1362)

[Reloaded] Create Loader | Time: 50ms
[Reloaded] Loading 1 Mod(s).
[Reloaded]
[Reloaded] Loading: Reloaded II Shared Lib: Reloaded.Hooks
[Reloaded] - AppId   : reloaded.sharedlib.hooks
[Reloaded] - Location: C:\Users\justi\OneDrive\바탕 화면\Reloaded-II\Mods\reloaded.sharedlib.hooks\ModConfig.json
[Reloaded] - LoadTime: 3ms
[Reloaded] Loaded via: C:\Users\justi\OneDrive\바탕 화면\Reloaded-II\Loader\x64\Bootstrapper\Reloaded.Mod.Loader.Bootstrapper.dll
[Reloaded] Current Process Location: D:\SteamLibrary\steamapps\common\P5R\P5R.exe
[Reloaded] Loading 9 Mod(s).
[Reloaded]
[Reloaded] Loading: Library: Reloaded.Memory.Sigscan for Reloaded II
[Reloaded] - AppId   : Reloaded.Memory.SigScan.ReloadedII
[Reloaded] - Location: C:\Users\justi\OneDrive\바탕 화면\Reloaded-II\Mods\Reloaded.Memory.SigScan.ReloadedII\ModConfig.json
[Reloaded] - LoadTime: 12ms
[Reloaded]
[Reloaded] Loading: CRI FileSystem V2 Hook
[Reloaded] - AppId   : crifs.v2.hook
[Reloaded] - Location: C:\Users\justi\OneDrive\바탕 화면\Reloaded-II\Mods\crifs.v2.hook\ModConfig.json
[Reloaded] - LoadTime: 42ms
[Reloaded]
[Reloaded] Loading: File Emulation Framework: Base Mod
[Reloaded] - AppId   : reloaded.universal.fileemulationframework
[Reloaded] - Location: C:\Users\justi\OneDrive\바탕 화면\Reloaded-II\Mods\reloaded.universal.fileemulationframework\ModConfig.json
Starting FileEmulationFramework
[R-II SteamHook] SteamAPI_RestartAppIfNecessary hooked successfully.
[R-II SteamHook] SteamAPI_IsSteamRunning hooked successfully.
[Reloaded] - LoadTime: 43ms
[Reloaded]
[Reloaded] Loading: AWB Emulator for File Emulation Framework
[Reloaded] - AppId   : reloaded.universal.fileemulationframework.awb
[Reloaded] - Location: C:\Users\justi\OneDrive\바탕 화면\Reloaded-II\Mods\reloaded.universal.fileemulationframework.awb\ModConfig.json
[R-II SteamHook] Found Steam Library Entry with Id 1687950. Dropping steam_appid.txt.
[Reloaded] Setting Up Hooks (Async) | Time: 135ms
Starting AWB.Stream.Emulator
[Reloaded] - LoadTime: 37ms
[Reloaded]
[Reloaded] Loading: AWB Emulator Support for CRI FileSystem V2 Hook
[Reloaded] - AppId   : CriFs.V2.Hook.Awb
[Reloaded] - Location: C:\Users\justi\OneDrive\바탕 화면\Reloaded-II\Mods\CriFs.V2.Hook.Awb\ModConfig.json
[Reloaded] - LoadTime: 9ms
[Reloaded]
[Reloaded] Loading: PAK Emulator for File Emulation Framework
[Reloaded] - AppId   : reloaded.universal.fileemulationframework.pak
[Reloaded] - Location: C:\Users\justi\OneDrive\바탕 화면\Reloaded-II\Mods\reloaded.universal.fileemulationframework.pak\ModConfig.json
Starting PAK.Stream.Emulator
[Reloaded] - LoadTime: 14ms
[Reloaded]
[Reloaded] Loading: BF Emulator for File Emulation Framework
[Reloaded] - AppId   : reloaded.universal.fileemulationframework.bf
[Reloaded] - Location: C:\Users\justi\OneDrive\바탕 화면\Reloaded-II\Mods\reloaded.universal.fileemulationframework.bf\ModConfig.json
[Reloaded] [LoaderAPI] Warning: GetController<IReloadedHooks> returned null.
Starting BF.File.Emulator
Error while starting mod: reloaded.universal.fileemulationframework.bf
[Reloaded] Failed to Load Reloaded-II.
Could not find a part of the path 'C:\Users\justi\OneDrive\바탕 화면\Reloaded-II\Mods\reloaded.universal.fileemulationframework.bf\Libraries\Persona4Golden\Modules\Field\Functions.json'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at AtlusScriptLibrary.Common.Libraries.Serialization.ExternalJsonPathConverter.ListConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at AtlusScriptLibrary.Common.Libraries.LibraryLookup.EnsureInitialized()
   at AtlusScriptLibrary.Common.Libraries.LibraryLookup.GetLibrary(String name)
   at BF.File.Emulator.BfEmulator..ctor(Logger log, Boolean dumpFiles, Game game)
   at BF.File.Emulator.Mod..ctor(ModContext context)
   at BF.File.Emulator.Template.Startup.StartEx(IModLoaderV1 loaderApi, IModConfigV1 modConfig)
   at Reloaded.Mod.Loader.Mods.Structs.ModInstance.Start(IModLoader loader)
   at Reloaded.Mod.Loader.Mods.PluginManager.StartMod(ModInstance instance)
   at Reloaded.Mod.Loader.Mods.PluginManager.LoadMods(List`1 modPaths)
   at Reloaded.Mod.Loader.Loader.LoadModsWithDependencies(IEnumerable`1 modsToLoad, List`1 allMods)
   at Reloaded.Mod.Loader.Loader.LoadForAppConfig(IApplicationConfig applicationConfig)
   at Reloaded.Mod.Loader.EntryPoint.LoadMods(IReloadedHooks hooks)
   at Reloaded.Mod.Loader.EntryPoint.<>c__DisplayClass14_0.<SetupLoader2>b__1()
   at Reloaded.Mod.Loader.EntryPoint.ExecuteTimed(String text, Action action)
   at Reloaded.Mod.Loader.EntryPoint.SetupLoader2(EntryPointParameters* parameters)
   at Reloaded.Mod.Loader.EntryPoint.SetupLoader(EntryPointParameters* parameters)
A log is available at: C:\Users\justi\AppData\Roaming\Reloaded-Mod-Loader-II\Logs\2024-03-18 03.54.08 ~ P5R.txt

**Comment by Sewer56** [comment]
Try deleting `C:\Users\justi\OneDrive\바탕 화면\Reloaded-II\Mods\reloaded.universal.fileemulationframework.bf` and letting the launcher re-download it, see what happens.

**Comment by yougotrespect** [comment]
> Try deleting `C:\Users\justi\OneDrive\바탕 화면\Reloaded-II\Mods\reloaded.universal.fileemulationframework.bf` and letting the launcher re-download it, see what happens.
> 
> I'd also advise against putting Reloaded in a folder with non-ASCII characters, e.g. Chinese, Japanese, Korean. While Reloaded itself handles this fine, game code in many cases doesn't.

great
great
very very good
"with non-ASCII characters, e.g. Chinese, Japanese, Korean"<---this one was the problem
I need to download reloaded2 in english folder

thanks Sewer56
you helped me a lot

**Comment by Sewer56** [comment]
No problem :+1:
